### PR TITLE
i make readme look pro

### PR DESCRIPTION
**Pull request by tesinormed**
fix gramar to

### CODE REVIEW

**Comment by adex720** [comment]
I also made French translation

**Comment by tesinormed** [comment]
i will fix later it is 2 am

**Comment by jonatench** [comment]
read through readme it look super propro

**Comment by tesinormed** [comment]
thx i wu ill wi willl fix then you xan merge

**Comment by jonatench** [comment]
pro pro pro

**Comment by tesinormed** [comment]
i fix go comit

**Comment by jonatench** [comment]
pog have to read new readme tho

**Comment by jonatench** [comment]
looking pog shall merge

**Pull request merged**
